### PR TITLE
Adopt std::to_array

### PR DESCRIPTION
**Pull request by tatsuhiro-t**

### CODE REVIEW

**Comment by lhuang04** [comment]
This broke our recent ngtcp2 build. The `to_array` seems a [C++ 20 feature](https://en.cppreference.com/w/cpp/container/array/to_array).  Could you take a look?

```
third-party/ngtcp2/examples/server.cc:336:28: error: no member named 'to_array' in namespace 'std'
      auto trailers = std::to_array({
                      ~~~~~^
third-party/ngtcp2/examples/server.cc:401:26: error: no member named 'to_array' in namespace 'std'
    auto trailers = std::to_array({
                    ~~~~~^
third-party/ngtcp2/examples/server.cc:559:26: error: no member named 'to_array' in namespace 'std'
    auto trailers = std::to_array({
                    ~~~~~^
```

**Comment by lhuang04** [comment]
I saw a similar build error in your [CI run](https://github.com/ngtcp2/ngtcp2/actions/runs/8579783675/job/23515148489)
```
#7 148.7 server.cc:335:28: error: no member named 'to_array' in namespace 'std'
#7 148.7       auto trailers = std::to_array({
#7 148.7                       ~~~~~^
#7 148.8 server.cc:398:26: error: no member named 'to_array' in namespace 'std'
#7 148.8     auto trailers = std::to_array({
#7 148.8                     ~~~~~^
#7 148.8 server.cc:546:26: error: no member named 'to_array' in namespace 'std'
#7 148.8     auto trailers = std::to_array({
#7 148.8                     ~~~~~^
#7 149.3 3 errors generated.
#7 149.3 make[2]: *** [Makefile:3150: wsslserver-server.o] Error 1
#7 149.3 make[2]: *** Waiting for unfinished jobs....
#7 150.7 make[2]: Leaving directory '/ngtcp2/examples'
#7 150.7 make[1]: *** [Makefile:558: all-recursive] Error 1
#7 150.7 make[1]: Leaving directory '/ngtcp2'
#7 150.7 make: *** [Makefile:463: all] Error 2
#7 ERROR: process "/bin/sh -c apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends         git gcc clang-12 make binutils autoconf automake autotools-dev libtool         pkg-config libev-dev libjemalloc-dev         libev4 libjemalloc2 ca-certificates mime-support         llvm-12 libasan5 libubsan1 &&     git clone --depth 1 -b v5.7.0-stable https://github.com/wolfSSL/wolfssl &&     cd wolfssl && autoreconf -i &&     ./configure --enable-all --enable-aesni --enable-harden         --enable-keylog-export --disable-ech &&     make -j$(nproc) && make install && cd .. && rm -rf wolfssl &&     git clone --recursive --shallow-submodules --depth 1 https://github.com/ngtcp2/nghttp3 &&     cd nghttp3 &&     autoreconf -i &&     ./configure --enable-lib-only         CC=clang-12         CXX=clang++-12         LDFLAGS=\"-fsanitize=address,undefined -fno-sanitize-recover=undefined\"         CPPFLAGS=\"-fsanitize=address,undefined -fno-sanitize-recover=undefined -g3\" &&     make -j$(nproc) && make install && cd .. && rm -rf nghttp3 &&     git clone --recursive --shallow-submodules --depth 1 -b $NGTCP2_BRANCH https://github.com/ngtcp2/ngtcp2 &&     cd ngtcp2 &&     autoreconf -i &&     ./configure         CC=clang-12         CXX=clang++-12         LDFLAGS=\"-fsanitize=address,undefined -fno-sanitize-recover=undefined\"         CPPFLAGS=\"-fsanitize=address,undefined -fno-sanitize-recover=undefined -g3\"         --with-wolfssl &&     make -j$(nproc) && make install &&     cp examples/wsslserver examples/wsslclient examples/h09wsslserver examples/h09wsslclient /usr/local/bin &&     cd .. &&     rm -rf ngtcp2 &&     rm -rf /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a /usr/local/lib/pkgconfig/*ssl.pc /usr/local/include/wolfssl/* &&     apt-get -y purge git g++ clang-12 make binutils autoconf automake         autotools-dev libtool pkg-config         libev-dev libjemalloc-dev &&     apt-get -y autoremove --purge &&     rm -rf /var/log/*" did not complete successfully: exit code: 2
```

**Comment by tatsuhiro-t** [comment]
ngtcp2 requires C++20 for examples.  The latest CI worked flawlessly.  What is the problem?

**Comment by lhuang04** [comment]
I see. Good to know that ngtcp2 requires C++20 for examples. We will incorporate this requirement on our end.

**Pull request merged**
