### PR TITLE
ngtcp2_conn_write_stream() returns incorrect error

### PR DESCRIPTION
**Pull request by NKTelnet**
when the congestion window size of a connection is small (lower than 36?), ngtcp2_conn_write_stream() may return ERR_STREAM_DATA_BLOCKED, but the flow control windows are big enough at that time.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR.
There are some issues around NGTCP2_ERR_NOBUF in ngtcp2 and I have a plan to review its usage.
There are similar error code like NGTCP2_ERR_CONGESTION, but it is a bit unclear which error code should be returned.  This issue will be handled in the process.

**Comment by NKTelnet** [comment]
I agree and I think there should not be NGTCP2_ERR_NOBUF error.  It should return NGTCP2_ERR_CONGESTION. All NGTCP2_ERR_NOBUF should be removed and the caller should set the buffer to UDP packet size.

**Comment by NKTelnet** [comment]
By the way, the NGTCP2_MIN_PKTLEN should be set to 37 acording to your code. NGTCP2_MIN_PKTLEN is not the mininal quic packet size, but for congestion control

**Comment by tatsuhiro-t** [comment]
It is good idea to set NGTCP2_MIN_PKTLEN to minimum packet size... the thing is some of the quic header is variable length.
I think NGTCP2_ERR_NOBUF purely indicates that the buffer size application set is too small without congestion control applied.  It is not needed if application sets enough packet size.

**Comment by tatsuhiro-t** [comment]
NGTCP2_ERR_NOMEM is now not surfaced from ngtcp2 API.
I also removed NGTCP2_ERR_CONGESTION.  Now APIs return 0 in the situation that these 2 error codes are returned previously.  I think this is ok because all app should do is keep reading and wait for congestion window to grow.  There is no special treatment for congestion.
NGTCP2_MIN_PKTLEN is also removed.  If we cannot write anything in congestion limited buffer, try ACK only packet without the restriction.
I also fixed couple of bugs and assertion errors.

**Pull request closed without merging**
