### PR TITLE
Add BBR congestion control.

### PR DESCRIPTION
**Pull request by xiaozhihong**
Hi, I'm the developer of [srs](https://github.com/ossrs/srs) , thanks to all the contributors of ngtcp2, it's an awesome project. I use ngtcp2 in my project [srs](https://github.com/ossrs/srs) to transport media streams between different servers. And cubic cc can't meet my needs when transmitting stream in a complex network(long RTT, high loss present), and I add BBR to make it good.
I implement the BBR algorithm described in [bbr](https://tools.ietf.org/html/draft-cardwell-iccrg-bbr-congestion-control-00), and test it uses a live media stream from the U.S. to China.

The picture blew is transmit live media stream using cubic cc.
cubic
This picture blew is transmit live media stream using BBR cc.
bbr

I hope you can help me to check the code, and make more test cases.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR.  I have not fully understood BBR and read this code, but this is quite interesting.  It looks like pacer needs some work, like hooking up to timers and utilize send quantum for GSO.  I'll figure out how to fix these issues.

**Comment by xiaozhihong** [comment]
> Thank you for PR. I have not fully understood BBR and read this code, but this is quite interesting. It looks like pacer needs some work, like hooking up to timers and utilize send quantum for GSO. I'll figure out how to fix these issues.

Yes, some code needs to refine which I added "TODO: FIXME:" content in files.
And I thought we can take more info to congestion control callback functions, like pass the rate sample estimate info and so on.
And the code about how to pace send need more consideration.
Let's do it well, it could be a long-time work.

**Comment by tatsuhiro-t** [comment]
Based on this PR, I made fixes and improvements.  See the WIP https://github.com/ngtcp2/ngtcp2/tree/bbr-cc
Aside from the sad situation of timer resolution of userspace event loop, BBR performs equally well with Cubic and outperforms it with loss (which is expected because BBR pretty much ignores losses).
I added new API to set packet next send time, which is a separate function from ngtcp2_conn_writev_stream for GSO usecase.
Needs more polishments.

**Comment by tatsuhiro-t** [comment]
BBR added as of 53b38c0471ba1a205440886e156e5b3c1bbb727f

**Comment by xiaozhihong** [comment]
> Based on this PR, I made fixes and improvements. See the WIP https://github.com/ngtcp2/ngtcp2/tree/bbr-cc
> Aside from the sad situation of timer resolution of userspace event loop, BBR performs equally well with Cubic and outperforms it with loss (which is expected because BBR pretty much ignores losses).
> I added new API to set packet next send time, which is a separate function from ngtcp2_conn_writev_stream for GSO usecase.
> Needs more polishments.

Good news & nice code, I will test it frequently and find issues on it.

**Comment by ruanshanshan** [comment]
> Based on this PR, I made fixes and improvements. See the WIP https://github.com/ngtcp2/ngtcp2/tree/bbr-cc
> Aside from the sad situation of timer resolution of userspace event loop, BBR performs equally well with Cubic and outperforms it with loss (which is expected because BBR pretty much ignores losses).
> I added new API to set packet next send time, which is a separate function from ngtcp2_conn_writev_stream for GSO usecase.
> Needs more polishments.

Is this pr bbr1 or bbr2？

**Comment by tatsuhiro-t** [comment]
BBR v1

**Pull request closed without merging**
