### PR TITLE
Write ACK to Server Initial from client

### PR DESCRIPTION
**Pull request by JunqiWang**
Some implementations of server don't make indications of client having received SHLO and do expect ACK.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
I think server should handle this situation without ACK from client.  QUIC is still early stage and those servers should be fixed.
I'll wait for next quic draft to see any changes in this area.

**Comment by JunqiWang** [comment]
I agree server should handle the case. But I think client should also send ACK so that server can start having RTT samples earlier.

**Comment by tatsuhiro-t** [comment]
Getting rtt sample earlier is valid argument.  QUIC wg will change the rules of packtization of Initials in the next draft, so I will revisit this issue when the next draft is published.

**Comment by JunqiWang** [comment]
sounds good. Closing

**Comment by mjoras** [comment]
Can we repen this? The language in the spec is actually now saying that you should acknowledge data at an encryption level before discarding keys:

> An endpoint cannot discard keys for a given encryption level unless it has both received and acknowledged all CRYPTO frames for that encryption level and when all CRYPTO frames for that encryption level have been acknowledged by its peer.

**Pull request closed without merging**
