### PR TITLE
CMake support and autotools fixups

### PR DESCRIPTION
**Pull request by Lekensteyn**
Hi!

This PR introduces CMake support and is based on the same port I did for nghttp2. It requires CMake 3.1 because of the use of the `CXX_STANDARD` option.

`autoreconf -i` + `configure --enable-werror` + `make -j10` takes 6.1 + 3.8 + 5.8 = 15.7s
`cmake -GNinja` + `ninja` takes 3 + 3.9s = 6.9s
Productivity increases!

Some open TODOs/discussion points:
- autotools has warnings disabled by default and `--enable-werror` controls whether they are enabled or not (together with `-Werror`). Should autotools be adjusted to cmake behavior and enable warnings by default, but control -Werror through an option?
- <del>autotools does not install headers, probably an omission</del> taken care of in latest master
- travis has not enabled osx (+clang) build, maybe it could be done later
- `DEBUGBUILD` macro seems unused, should it be removed?
- The examples have a number of compiler warnings (unused variables, `-Wnoexcept-type`, etc.)

travis does not seem to be enabled at all: https://travis-ci.org/ngtcp2/ngtcp2

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR!


>    autotools has warnings disabled by default and --enable-werror controls whether they are enabled or not (together with -Werror). Should autotools be adjusted to cmake behavior and enable warnings by default, but control -Werror through an option?

It is preferable, but I'm fine with the current cmake behaviour.

> autotools does not install headers, probably an omission

It is probably a bug.  I've never run `make install`.

> travis has not enabled osx (+clang) build, maybe it could be done later

osx build causes some errors which I have no time to debug.  So it is turned off for now.

>  DEBUGBUILD macro seems unused, should it be removed?

It is currently not used.  You can omit it in cmake.

> The examples have a number of compiler warnings (unused variables, -Wnoexcept-type, etc.)

Will check.

**Comment by Lekensteyn** [comment]
> It is preferable, but I'm fine with the current cmake behaviour.

Are you fine with current cmake or autotools behavior? As in, should autotools be changed or not?

**Comment by tatsuhiro-t** [comment]
> Are you fine with current cmake or autotools behavior? As in, should autotools be changed or not?

I should say I am fine with current cmake behaviour.
If change is required in autotools version, it would be done in an another PR.

**Comment by tatsuhiro-t** [comment]
@Lekensteyn This PR looks good to me.  Do you think this PR is ready for merge?

**Comment by Lekensteyn** [comment]
Yes I think it is ready for merge. Comparing the changes since this PR and master, it seems that no new files/other changes need to be done before merging.

The other issues can be addressed in future changes I think.

**Comment by tatsuhiro-t** [comment]
Thank you.  Merged now.

**Pull request merged**
